# 1.Print 'Hello HCIA'.

In [4]:
print ('Hello HCIA')


Hello HCIA


# 2.Define two variables and calculate their sum.

In [5]:
a = 5
b = 3
print (a + b)


8


# 3.Define a list and replicate in three different ways.

In [3]:
a = [1, 2, 3]
b = a 
c = a.copy()
d = []
for i in a:
    d.append(i)
print (b, c, d)

[1, 2, 3] [1, 2, 3] [1, 2, 3]


# 4.Define two lists and merge them together.

In [6]:
a = [1, 3, 5]
b = [2, 4, 6]
print (a + b)


[1, 3, 5, 2, 4, 6]


# 5. Get the last element of the list and print it.

In [7]:
list = [1, 2, 3]
list [-1]


3

# 6.Define a tuple that contains only one element.

In [5]:
tuple = (1)
print(tuple)


1


# 7.Define a three-line long string.

In [4]:
list = '''123
qwe
asd'''
print (list)


123
qwe
asd


# 8.Define a tuple and then use the 'for loop' to print all the elements.

In [2]:
t = (1, 2, 3, 4, 5)
for i in t:
    print (i)
    

1
2
3
4
5


# 9.Define a function to do Multiplication, such as Mul(8,6),and its output 48.

In [11]:
def mult(a,b):
    c = a*b
    print (c)
    
mult(6, 8)


48


# 10.Import numpy and use numpy to define an array, the its shape  is (5,5) and all its elements is 0.

In [6]:
import numpy

array = numpy.zeros((5, 5))
print (array)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# 11.Import numpy and use numpy to define an array, the shape is (4,6) and all elements is 0.

In [7]:
import numpy

array = numpy.zeros((4, 6))
print (array)


[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


# 12.Use numpy.arrange() to generate an array of shape(15,), then modify the shape to(3,5).

In [8]:
import numpy

arrange = numpy.arange(15,)
arrange = arrange.reshape(3, 5)
print (arrange)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


# 13.Define two matrices, then calculate and print the result of their point multiplication.

In [15]:
import numpy

arrang1 = numpy.arange(8).reshape(4, 2)
arrang2 = numpy.arange(8).reshape(4, 2)

print (numpy.multiply(arrang1, arrang2))


[[ 0  1]
 [ 4  9]
 [16 25]
 [36 49]]
